apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mytestcicd-app
spec:
  destination:
    name: ''
    namespace: mytestcicd-app
    server: 'https://kubernetes.default.svc'
  source:
    path: 07-Service
    repoURL: 'https://github.com/amitvashisttech/argo-cd-dev.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
